### PR TITLE
no model changes for LXD_FAKE disks

### PR DESCRIPTION
**Pull request by dejonghb**
hack for skipping disks created with model == 'LXD_FAKE' for use in lxd containers

### CODE REVIEW

**Review by JeffreyDevloo — CHANGES_REQUESTED** [review]
This is a good temporary solution but something better could be thought out

**Comment by dejonghb** [comment]
Maybe these disks could get some extra hint they were "manual" created instead of "autodetected"? Using the model for this is certainly a quick hack that can be improved.
This might also help for  #1814 where the modelled size can/should then overrule what the directory/device underneath reports (in case that would be larger ;-) )?

**Comment by domsj** [comment]
While setting up ovs inside an lxd container I encountered the following error:
https://github.com/openvstorage/framework/blob/develop/ovs/lib/storagerouter.py#L334

The is_mounted check failed, because there is nothing to be mounted on the fakedisk in my test setup.

Perhaps for manually added disks it makes more sense to check whether some marker file is there?

**Comment by sjovdnbos** [comment]
Closed due to deviation being too far from current current branch.

**Pull request closed without merging**
