### PR TITLE
FWK-763 - increased etcd timout values

### PR DESCRIPTION
**Pull request by pploegaert**

### CODE REVIEW

**Comment by khenderick** [comment]
Sad, but unfortunately the only way we can keep Etcd running

**Comment by pploegaert** [comment]
```
2016-08-05 04:49:34 31700 +0200 - ovs52n252 - 24829/139664197007168 - extensions/etcdconfiguration - 3 - WARNING - Call to _get (key: /ovs/framework/messagequeue) took 1.08427810669s
2016-08-05 05:56:18 27200 +0200 - ovs52n252 - 24829/139664197007168 - extensions/etcdconfiguration - 25 - WARNING - Call to _get (key: /ovs/framework/messagequeue) took 15.0017399788s
2016-08-05 05:56:18 27200 +0200 - ovs52n252 - 24829/139664197007168 - extensions/watcher - 26 - DEBUG - [framework] Unexpected exception: Raft Internal Error : etcdserver: request timed out
2016-08-05 05:56:18 27200 +0200 - ovs52n252 - 24829/139664197007168 - extensions/watcher - 27 - DEBUG - [framework] One of the master services is unavailable
2016-08-05 05:56:21 57400 +0200 - ovs52n252 - 57544/139897978885952 - extensions/etcdconfiguration - 0 - WARNING - Call to _get (key: /ovs/framework/logging) took 1.61168909073s
2016-08-05 05:56:21 57500 +0200 - ovs52n252 - 57544/139897978885952 - extensions/watcher - 1 - DEBUG - [framework] Starting service
2016-08-05 05:56:21 57500 +0200 - ovs52n252 - 57544/139897978885952 - extensions/watcher - 2 - DEBUG - [framework] Waiting for master services
2016-08-05 05:56:23 40500 +0200 - ovs52n252 - 57544/139897978885952 - extensions/watcher - 3 - DEBUG - [framework] Master services available
2016-08-05 05:56:23 81200 +0200 - ovs52n252 - 57619/139669388740416 - extensions/watcher - 0 - DEBUG - [framework] Starting service
2016-08-05 05:56:23 81200 +0200 - ovs52n252 - 57619/139669388740416 - extensions/watcher - 1 - DEBUG - [framework] Checking master services
2016-08-05 07:00:46 91700 +0200 - ovs52n252 - 57619/139669388740416 - extensions/etcdconfiguration - 15 - WARNING - Call to _get (key: /ovs/framework/messagequeue) took 1.36786198616s
2016-08-05 08:51:36 77000 +0200 - ovs52n252 - 57619/139669388740416 - extensions/etcdconfiguration - 25 - WARNING - Call to _get (key: /ovs/framework/messagequeue) took 60.049975872s
2016-08-05 08:51:36 77000 +0200 - ovs52n252 - 57619/139669388740416 - extensions/watcher - 26 - DEBUG - [framework] Unexpected exception: Connection to etcd failed due to ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=2379): Read timed out. (read timeout=60)",)
2016-08-05 08:51:36 77000 +0200 - ovs52n252 - 57619/139669388740416 - extensions/watcher - 27 - DEBUG - [framework] One of the master services is unavailable
2016-08-05 08:51:37 48500 +0200 - ovs52n252 - 91314/140521229858624 - extensions/watcher - 0 - DEBUG - [framework] Starting service
2016-08-05 08:51:37 48500 +0200 - ovs52n252 - 91314/140521229858624 - extensions/watcher - 1 - DEBUG - [framework] Waiting for master services
2016-08-05 08:51:38 44000 +0200 - ovs52n252 - 91314/140521229858624 - extensions/watcher - 2 - DEBUG - [framework] Master services available
2016-08-05 08:51:38 73400 +0200 - ovs52n252 - 91343/140396094105408 - extensions/watcher - 0 - DEBUG - [framework] Starting service
2016-08-05 08:51:38 73400 +0200 - ovs52n252 - 91343/140396094105408 - extensions/watcher - 1 - DEBUG - [framework] Checking master services
2016-08-05 09:07:37 84300 +0200 - ovs52n252 - 91343/140396094105408 - extensions/etcdconfiguration - 6 - WARNING - Call to _get (key: /ovs/framework/messagequeue) took 1.02661204338s
2016-08-05 09:42:46 47600 +0200 - ovs52n252 - 124845/139822527113024 - extensions/watcher - 0 - DEBUG - [framework] Starting service
2016-08-05 09:42:46 47600 +0200 - ovs52n252 - 124845/139822527113024 - extensions/watcher - 1 - DEBUG - [framework] Waiting for master services
2016-08-05 09:42:47 68300 +0200 - ovs52n252 - 124845/139822527113024 - extensions/watcher - 2 - DEBUG - [framework] Master services available
2016-08-05 09:42:48 17800 +0200 - ovs52n252 - 124859/139893597439808 - extensions/watcher - 0 - DEBUG - [framework] Starting service
2016-08-05 09:42:48 17900 +0200 - ovs52n252 - 124859/139893597439808 - extensions/watcher - 1 - DEBUG - [framework] Checking master services
2016-08-05 12:50:15 19900 +0200 - ovs52n252 - 124859/139893597439808 - extensions/etcdconfiguration - 17 - WARNING - Call to _get (key: /ovs/framework/messagequeue) took 1.07619810104s
2016-08-05 14:24:12 10100 +0200 - ovs52n252 - 124859/139893597439808 - extensions/etcdconfiguration - 23 - WARNING - Call to _get (key: /ovs/framework/messagequeue) took 1.02638101578s
2016-08-05 14:45:08 80500 +0200 - ovs52n252 - 124859/139893597439808 - extensions/etcdconfiguration - 27 - WARNING - Call to _get (key: /ovs/framework/messagequeue) took 1.15181112289s
```

**Comment by pploegaert** [comment]
timeouts of up to 15 seconds
after updating etcd timeout values - no raft errors for now ...

**Comment by pploegaert** [comment]
openvstorage 2.7.2-rev.3835.9f486e5

**Comment by pploegaert** [comment]
Timeout values need to be reduced as etcd fails to start,
new values 2500/25000 appears to work - further testing on NB required
reduced snapshot-count of 10000 -> 2500 to reduce impact on this part too
Disk IO / network might interfere with etcd ... we might consider the network tuning via tc too:
https://github.com/coreos/etcd/blob/master/Documentation/tuning.md

**Pull request merged**
